name: company
run-name: Setting up the company database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: Test Output
        run: echo "Hello, World!"
  conntect-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show databases
        run: mysql -h "$DB_HOSTNAME" --port=3306 -u"$DB_USERNAME" -p"$DB_PASSWORD" -e "show databases;"
